version: "3"
services:
  jammed-node-app:
    # build image from Dockerfile in current directory
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
    # alternatively we can specify env file:
    # env_file:
    #   - ./.env
  # postgres ...
