- name: Install obsidian
  become: true
  shell: snap install obsidian --classic
  tags:
    - obsidian
    - apps

- name: Install unrar
  apt: name=unrar
  tags:
    - unrar
    - apps

- name: Install vscode
  become: true
  shell: sudo snap install --classic code
  tags:
    - vscode
    - apps

# See https://code.visualstudio.com/docs/editor/extension-marketplace#_command-line-extension-management
# and https://stackoverflow.com/a/34339780.
- name: Install vscode extensions
  shell:
    - code --install-extension obrejla.netbeans-light-theme
    - code --install-extension vscode-icons-team.vscode-icons
    - code --install-extension aaron-bond.better-comments
    - code --install-extension editorconfig.editorconfig
    - code --install-extension streetsidesoftware.code-spell-checker
    # extension docs: In the VS Code command palette, run the TypeScript: Select TypeScript version command.
    - code --install-extension ms-vscode.vscode-typescript-next
    # extension docs:
    # The extension uses the ESLint library installed in the opened workspace folder. If the folder
    # doesn't provide one the extension looks for a global install version. If you haven't installed
    # ESLint either locally or globally do so.
    - code --install-extension dbaeumer.vscode-eslint
  tags:
    - vscode
    - apps

