- name: Install ZSH
  apt: name=zsh
  tags: &tags_for_zsh_tasks [ 'install', 'zsh' ]
    
- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  # using the defined tags above (not sure)
  tags: *tags_for_zsh_tasks

# Omitted the part to become another user (for security?) as well as checking the conf file . 
# For more information, see https://github.com/ThePrimeagen/ansible/blob/master/tasks/zsh-setup.yml.

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

- name: Update our zshrc
  shell: sed -i 's/plugins=(git)/plugins=(git zsh-autosuggestions)'
  tags: *tags_for_zsh_tasks

# add more