- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/shell-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/i3.yml
    - include: tasks/other-apps.yml