# Specific configuration for development
version: "3"
services:
  node-app:
    build:
      # location of Dockerfile
      context: .
      args:
        COMPOSE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run start:watch
